[package]
name = "quantcast-exercise"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }

[[bin]]
name = "most_active_cookie"
path = "src/most_active_cookie.rs"