[package]
name = "quantcast-exercise"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }

[dev-dependencies]
assert_fs = "1.0.13"
assert_cmd = "2.0.12"
predicates = "3.0.4"

[[bin]]
name = "most_active_cookie"
path = "src/most_active_cookie.rs"
